# pytest.ini
[pytest]
anyio_backend = asyncio
anyio_backends = asyncio
# Carpeta donde buscar tests
testpaths = app/tests

# Archivos y funciones de test que detectará
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones por defecto (como si ejecutaras pytest -s -v)
addopts = -s -v

# Mostrar logs en consola
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

# Otros ajustes
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

# credenciales para login
auth_username = bosomossad
auth_password = mS92KtzQQ5WTrrJrKFrM