[pytest]
testpaths = app/tests
python_files = test_*.py tests_*.py
python_classes = Test*
python_functions = test_*
addopts = -q

log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

markers =
    integration: requiere BBDD, red externa o credenciales reales
